### ISSUE TITLE
Difficulty with importing MaxQuant output

### ISSUE THREAD

**Issue by fgarbicz** [CNIC-Proteomics/iSanXoT#10]
Dear Jose,
I find this software very interesting and I'm trying to use it on my TMT proteomics data. I am trying to use MaxQuant output file: msmsScans.txt as described in the documentation. I am not sure what to do at the stage of indicating identifiers (my background is strictly genomic and transcriptomic with some basic downstream proteomics dataviz, however I might be missing something here).

![image](https://github.com/CNIC-Proteomics/iSanXoT/assets/65818371/8398c0dd-4aea-4139-9a4a-e2f482ce0c70)

after trying to create adapted input file, I am getting the error below.

`CREATEIDQ - 35636 - 11/04/2023 07:12:14 PM - INFO - executing CREATE_IDQ module ---
CREATEIDQ - 35636 - 11/04/2023 07:12:14 PM - INFO - reading the experiment task-table
CREATEIDQ - 35636 - 11/04/2023 07:12:14 PM - INFO - processing the input file: read, add exp
CREATEIDQ - 35636 - 11/04/2023 07:12:22 PM - INFO - reading the level task-table
CREATEIDQ - 35636 - 11/04/2023 07:12:22 PM - INFO - adding level identifiers
Traceback (most recent call last):
File "D:\Programs\iSanXoT\resources\exec\python-3.9.7-win-x64\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
return self._engine.get_loc(casted_key)
File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'label_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "D:\Programs\iSanXoT\resources\src\cmds\createIDq.py", line 375, in <module>
main(sys.argv[1:])
File "D:\Programs\iSanXoT\resources\src\cmds\createIDq.py", line 205, in main
df = add_levelids(df, indata)
File "D:\Programs\iSanXoT\resources\src\cmds\createIDq.py", line 81, in add_levelids
ll = list(indata['label_name'])
File "D:\Programs\iSanXoT\resources\exec\python-3.9.7-win-x64\lib\site-packages\pandas\core\frame.py", line 3458, in __getitem__
indexer = self.columns.get_loc(key)
File "D:\Programs\iSanXoT\resources\exec\python-3.9.7-win-x64\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
raise KeyError(key) from err
KeyError: 'label_name'`

**Comment by jmrodriguezc** [comment]
Dear Filip,
First of all, I apologize for the delay. I am now quite busy, and I have just seen your issue.
In this version, it is mandatory to include an ‘Experiment’ label.
![2023-11-27 151134](https://github.com/CNIC-Proteomics/iSanXoT/assets/29915053/f0ed6d7b-a122-48cf-b4b6-fb294ae6ae33)
 

Secondly, I recommend that you change the created identifiers. It is sufficient to include the following identifiers: ScanID (scan identifier) and PepID (peptide identifier):
 
We will stay in contact, and I will respond to you more quickly.
Best Regards,
J

**Comment by jmrodriguezc** [comment]
By the way, we have a new version in which it is not mandatory to add the 'Experiment' label. It will be released very soon.

Best Regards,
J
